# Generated by Django 3.1.1 on 2021-02-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_funcionario', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('SP', 'SP'), ('RJ', 'RJ'), ('SC', 'SC'), ('MG', 'MG'), ('MS', 'MS')], max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=120)),
                ('cpf', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='controle_estoque/media/images', verbose_name='Imagem')),
                ('data_admissao', models.DateField(auto_now_add=True, verbose_name='Admitido em')),
                ('data_demissao', models.DateField(auto_now_add=True, verbose_name='Demitido em')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_criado_por', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['funcionario'],
            },
        ),
    ]
