# Generated by Django 3.1.1 on 2021-02-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='criado_por',
        ),
    ]
