# Generated by Django 3.1.1 on 2020-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=300)),
                ('pessoa_contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.CharField(choices=[('SP', 'SP'), ('RJ', 'RJ'), ('SC', 'SC'), ('MG', 'MG'), ('MS', 'MS')], default='SP', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=150)),
                ('cargo_funcionario', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('SP', 'SP'), ('RJ', 'RJ'), ('SC', 'SC'), ('MG', 'MG'), ('MS', 'MS')], max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=300)),
                ('usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('cpf', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='controle_estoque/media/images', verbose_name='Imagem')),
                ('data_admissao', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('data_demissao', models.DateField(auto_now_add=True, verbose_name='Demitido em')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['funcionario'],
            },
        ),
    ]
