# Generated by Django 3.1.1 on 2020-10-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
