# Generated by Django 3.1.1 on 2020-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_auto_20200925_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
