# Generated by Django 3.1.1 on 2020-10-29 04:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_estoque', '0002_auto_20201029_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='VendasHistory',
        ),
        migrations.AlterModelOptions(
            name='vendashistory',
            options={'ordering': ['criado_em'], 'verbose_name': 'Histórico de Venda', 'verbose_name_plural': 'Histórico de Vendas'},
        ),
        migrations.AlterModelTable(
            name='vendashistory',
            table='vendas_history',
        ),
    ]
