# Generated by Django 3.1.1 on 2020-09-25 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0004_auto_20200925_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=150)),
                ('cargo_funcionario', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('SP', 'SP'), ('RJ', 'RJ'), ('SC', 'SC'), ('MG', 'MG'), ('MS', 'MS')], max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=300)),
                ('usuario', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='controle_estoque/media/images', verbose_name='Imagem')),
                ('data_admissao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_demissao', models.DateTimeField(auto_now_add=True, verbose_name='Demitido em')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['funcionario'],
            },
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
