# Generated by Django 3.1.1 on 2020-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0005_auto_20200925_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(auto_now_add=True, verbose_name='Demitido em'),
        ),
    ]
