# Generated by Django 3.1.1 on 2020-09-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0007_auto_20200925_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(choices=[('SP', 'SP'), ('RJ', 'RJ'), ('SC', 'SC'), ('MG', 'MG'), ('MS', 'MS')], default='SP', max_length=100),
        ),
    ]
